[workspace]
members = [
    "ffi_01_basic_snappy_binding",
    "ffi_02_basic_snappy_binding",
    "ffi_03_calling_rust_from_c", 
    "ffi_04_rust_callbacks",
    "ffi_05_rust_callbacks_02",
    "ffi_06_foreign_globals",
    "ffi_07_variadic_functions",
    "ffi_08_opaque_structs",
    "ffi_09_opaque_structs_02",
    "ffi_10_safer_ffi_01",
    "ffi_11_safer_ffi_02",
    "ffi_12_safer_ffi_03",
]
resolver = "2"

[workspace.dependencies]
libc = "0.2"
