[package]
name = "ffi_12_safer_ffi_03"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = [
    "staticlib",  # Ensure it gets compiled as a (static) C library
    # "cdylib",   # If you want a shared/dynamic C library (advanced)
    "lib",        # For `generate-headers`, `examples/`, `tests/` etc.
]

[[bin]]
name = "generate-headers"
required-features = ["headers"]  # Do not build unless generating headers.

[dependencies]
safer-ffi.features = [] # you may add some later on.
# Use `cargo add` or `cargo search` to find the latest values of x.y.z.
# For instance:
#   cargo add safer-ffi
safer-ffi.version = "0.1"

[features]
# If you want to generate the headers, use a feature-gate
# to opt into doing so:
headers = ["safer-ffi/headers"]
